# Generated by Django 5.0.1 on 2024-02-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
