# Generated by Django 5.0.1 on 2024-02-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitys', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_num',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitys.board', verbose_name='소속 게시판')),
            ],
        ),
    ]
