# Generated by Django 5.0.1 on 2024-02-16 14:10

import apps.score.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='작성일')),
                ('par', models.JSONField(default=apps.score.models.default_scores)),
                ('scores', models.JSONField(default=apps.score.models.default_scores)),
                ('total_score', models.IntegerField(default=36)),
                ('game_round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_score', to='games.round')),
                ('ground', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.golflocation', verbose_name='골프장')),
            ],
        ),
    ]
