# Generated by Django 5.0.1 on 2024-02-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_players_id_alter_game_players_name'),
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_score', to='games.round'),
        ),
    ]
