# Generated by Django 5.0.1 on 2024-02-05 08:17

import apps.score.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='scores',
            field=models.JSONField(default=apps.score.models.default_scores),
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='score',
            name='par',
            field=models.JSONField(default=apps.score.models.default_scores),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='플레이어'),
        ),
    ]
