# Generated by Django 5.0.1 on 2024-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.IntegerField(default=36),
        ),
    ]
