# Generated by Django 5.0.1 on 2024-02-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolfLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golf_name', models.CharField(max_length=50)),
                ('golf_address', models.CharField(max_length=50)),
                ('golf_latitude', models.FloatField()),
                ('golf_longitude', models.FloatField()),
                ('golf_detail', models.TextField(max_length=200)),
                ('golf_holes', models.IntegerField()),
            ],
        ),
    ]
