# Generated by Django 5.0.1 on 2024-02-16 14:10

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolfLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golf_image', models.ImageField(blank=True, upload_to='locations/images/')),
                ('golf_scale', models.TextField(blank=True)),
                ('golf_name', models.CharField(blank=True, max_length=50, null=True)),
                ('golf_address', models.CharField(blank=True, max_length=50, null=True)),
                ('golf_holes', models.IntegerField()),
                ('golf_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('golf_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('golf_detail', models.TextField(blank=True, max_length=255, null=True)),
                ('golf_running_date', models.TextField(blank=True, max_length=255, null=True)),
                ('golf_reservation', models.TextField(blank=True, max_length=255, null=True)),
                ('golf_fee', models.TextField(blank=True, max_length=255, null=True)),
                ('golf_phone', models.TextField(blank=True, max_length=31, null=True)),
                ('golf_homepage', models.TextField(blank=True, max_length=127, null=True)),
                ('golf_running_time', models.TextField(blank=True, max_length=127, null=True)),
                ('fav_num', models.IntegerField(default=0)),
                ('golf_rate', models.FloatField(default=5.0)),
                ('golf_rate_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='리뷰 내용')),
                ('photo', models.ImageField(blank=True, upload_to='review/photo/%Y/%m/%d', verbose_name='이미지')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='평점')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('rate_tag', models.CharField(default='five', max_length=10, verbose_name='태그')),
            ],
        ),
        migrations.CreateModel(
            name='LikeGolf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.golflocation')),
            ],
        ),
    ]
