# Generated by Django 5.0.1 on 2024-02-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golflocation',
            name='golf_image',
            field=models.ImageField(blank=True, upload_to='locations/images/'),
        ),
        migrations.AddField(
            model_name='golflocation',
            name='golf_scale',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='golflocation',
            name='golf_latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='golflocation',
            name='golf_longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
