# Generated by Django 5.0.1 on 2024-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golflocation',
            name='golf_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
