# Generated by Django 5.0.1 on 2024-02-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate_tag',
            field=models.CharField(default='five', max_length=10, verbose_name='태그'),
        ),
    ]
