# Generated by Django 5.0.1 on 2024-02-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_likegolf'),
    ]

    operations = [
        migrations.AddField(
            model_name='golflocation',
            name='fav_num',
            field=models.IntegerField(default=0),
        ),
    ]
