# Generated by Django 5.0.1 on 2024-02-13 07:07

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='리뷰 내용')),
                ('photo', models.ImageField(blank=True, upload_to='review/photo/%Y/%m/%d', verbose_name='이미지')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.golflocation')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
