# Generated by Django 5.0.1 on 2024-02-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='golflocation',
            name='golf_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='golflocation',
            name='golf_rate_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='평점'),
        ),
    ]
