# Generated by Django 5.0.1 on 2024-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=31, verbose_name='시/도')),
                ('town', models.CharField(max_length=31, verbose_name='군/구')),
            ],
        ),
    ]
