# Generated by Django 5.0.1 on 2024-02-16 14:10

import apps.games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_name', models.JSONField(null=True)),
                ('players_id', models.JSONField(null=True)),
                ('game_name', models.CharField(default='게임', max_length=9, verbose_name='게임이름')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.JSONField(default=apps.games.models.default_scores)),
                ('round_number', models.IntegerField()),
            ],
        ),
    ]
