# Generated by Django 5.0.1 on 2024-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_player_id_game_players_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players_id',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='players_name',
            field=models.JSONField(null=True),
        ),
    ]
