# Generated by Django 5.0.1 on 2024-02-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
